version: '2'
services:
  haproxy:
    image: library/haproxy
    ports:
      - '80:80'
      - '9090:9090'
    volumes:
       - ./config/haproxy:/usr/local/etc/haproxy:ro
    depends_on:
      - platform
      - portal
  platform:
    build: platform/.
    expose:
      - '9999'
    environment:
      - PUBLIC_URL
      - TWILIO_ACCOUNT_SID
      - TWILIO_AUTH_TOKEN
      - TWILIO_NUMBER_SID
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_DEFAULT_REGION
      - JWT_SECRET
  portal:
    build: portal/.
    expose:
     - '8181'
    environment:
      - PLATFORM_URL=http://platform:9999