version: '2'
services:
  platform:
    build: platform/.
    ports:
     - '9999:9999'
    environment:
      - TWILIO_ACCOUNT_SID
      - TWILIO_AUTH_TOKEN
      - TWILIO_NUMBER_SID
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - PUBLIC_URL