version: '2'
services:
  ngrok:
    image: wernight/ngrok
    command: ["ngrok", "http", "haproxy:80"]
  haproxy:
    image: library/haproxy
    expose:
      - '80'
    ports:
      - '9090:9090'
    volumes:
       - ./config/haproxy:/usr/local/etc/haproxy:ro
    depends_on:
      - platform
      - portal
  platform:
    extends:
      file: docker-compose.yml
      service: platform
    depends_on:
      - ngrok
    environment:
      - PUBLIC_URL=
      - NGROK_URL=http://ngrok:4040
  portal:
    extends:
      file: docker-compose.yml
      service: portal